config/routes.rb
Rails.application.routes.draw do

  get "/users/edit" => "users#settings"
  

  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "/:locale" do

    devise_for :users, skip: :omniauth_callbacks, :controllers => {:registrations => "users/registrations",
                                                                   :sessions      => "users/sessions" }

    resources :books
    resources :categories
    resources :orders
    resources :order_items
    resources :order_steps
    resources :addresses
    resources :users

    root 'books#home'
    get  '/settings',    to: 'users#settings'
    get  '/shop/search', to: 'books#search'
    get  '/clear_shopcart', to: 'orders#clear_cookies_shopcart'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  resources :books, only: [:index, :show], path: '/shop'
  resources :categories, only: [:show], path: '/shop/category/'
  resources :ratings, only: [:index, :create], path: '/rating'

  scope :orders do 
    put    '/update_shopcart_ajax', to: 'orders#update_shopcart_ajax'
    post    '/check_cupon_ajax', to: 'orders#check_cupon_ajax'
  end
  resources :orders

  resources :order_items

  devise_scope :user do
    get    '/settings', to: 'users#settings'
  end

  resources :order_steps
  resources :addresses, only: [:update]
  resources :users, only: [:settings, :update_data] do
    patch  '/update_data', to: 'users#update_data'
    patch  '/update_password', to: 'users#update_password'
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  validates :total_price, :state, presence: true
  before_validation :set_completed_date

  has_many :order_items, dependent: :destroy
  belongs_to :user
  belongs_to :credit_card

  has_one :billing_address, class_name: 'Address', foreign_key: 'order_billing_address_id'
  has_one :shipping_address, class_name: 'Address', foreign_key: 'order_shipping_address_id'
  has_one :cupon

  def state_enum
    %w(in_progress
       in_queue
       in_delivery
       delivered
       canceled)
  end

  aasm column: 'state', whiny_transitions: false do 
    state :in_progress, initial: true
    state :in_queue
    state :in_delivery 
    state :delivered 
    state :canceled

    event :process do
      transitions from: :in_progress, to: :in_queue
    end

    event :ship do
      transitions from: :in_queue, to: :in_delivery
    end

    event :complete do
      transitions from: [:in_queue, :in_delivery], to: :delivered
    end

    event :cancel do
      transitions from: [:in_queue, :in_delivery], to: :canceled
    end
  end

  def delivery_enum
    [['UPS Ground', '5.0'], ['UPS One Day', '10.0'], ['UPS Two Days', '20.0']]
  end

  scope :last_order_queue, -> (current_user) { 
    where(user_id: current_user.id, state: 'in_queue').last 
  }

  scope :in_queue, -> (current_user) { 
    where(user_id: current_user.id, state: 'in_queue').all 
  }

  scope :in_delivery, -> (current_user) {
    where(user_id: current_user.id, state: 'in_delivery').all
  }

  scope :delivered, -> (current_user) {
    where(user_id: current_user.id, state: 'delivered').all
  }

  def self.create_order(cookies, total_price, user_id)
    book_count = cookies.nil? ? 0 : cookies['book_count']
    order = Order.create(user_id: user_id,
                          total_price: total_price,
                          order_total: total_price + 5.0,
                          book_count: book_count.to_i)
    order.id
  end

  private
  
  def set_completed_date
    self.completed_date = 3.days.from_now
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :load_in_progress_order, only: [:show]
  load_and_authorize_resource except: [:update_shopcart_ajax, 
    :clear_cookies_shopcart,
     :check_cupon_ajax]

  def new
    get_books
  end

  def update_shopcart_ajax
    set_session(ShopcartUpdateService.new(@order, params).call)
    render nothing: true
  end

  def clear_cookies_shopcart
    cookies_delete
    redirect_to books_path
  end

  def check_cupon_ajax
    checking = Cupon.cheking(params[:value])
    msg = checking.empty? ? 'This code is not found' : checking_message(checking.first)
    render text: msg
  end

  def show
  end

  def index
    get_books
    [:in_queue, :in_delivery, :delivered].each do |item|
      instance_variable_set("@#{item}".to_sym,
        Order.public_send(item).last_by_current_user(current_user))
    end
  end

  def destroy
    clear_order
    cookies_delete
    set_session(0)
    redirect_to books_path
  end

  private

  def checking_message(first)
    str = 'Your discount is $' << first.discount.to_s << '. Continue?'
    first.use ? 'This code has been used' : str
  end

  def clear_order
    @order.order_items.destroy_all
    @order.update(total_price: 0.0, book_count: 0, order_total: 0.0)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.haml
.row
  .col-md-12
    %h1= t(:title_orders)
    - unless @books.empty?
      %h2.underlined-h2= t(:in_progress)
      .row.cart
        .col-md-12
          %table.table
            = render partial: "orders/partials/books_header"
            = render partial: "orders/partials/render_books" , locals: {books: @books, remove_link: false, qty_change: false}
        .col-md-6
          %a.btn.btn-primary.lnk-to-cart{:href => "/orders/new"}= t(:go_to_cart)
        .col-md-6.col-md-6
          .order-summary-line{:style => "float: right; padding-right: 110px;"}
            = t(:subtotal)
            %span= number_to_currency(@subtotal)
      %br/
    = render partial: "orders/partials/status", locals: {status: @in_queue, title: t(:in_queue)}
    = render partial: "orders/partials/status", locals: {status: @in_delivery, title: t(:in_delivery)}
    = render partial: "orders/partials/status", locals: {status: @delivered, title: t(:delivered)}
    %br/
    %br/

app/views/orders/new.html.erb
<h1><%= t(:title_cart) %></h1>
<% unless @books.empty? %>
<div class="row cart full_cart">
  <div class="col-md-12">
    <table class="table">
      <%= render partial: "orders/partials/books_header" %>
      <%= render partial: "orders/partials/render_books",  locals: {books: @books, remove_link: true, qty_change: true} %> 
    </table>
  </div>
  <div class="col-md-6 col-md-offset-6 clearfix order-summary-block">
    <div class="order-summary-line">
      <%= t(:subtotal) %> <span><%= number_to_currency(@subtotal) %></span>
    </div>
  </div>
  <div class="col-md-6">
    <% if current_user %>
    <%= button_to t(:empty_cart), @order, :method => "delete", :class => "btn btn-default",  data: { confirm: t(:are_you_sure) } %>
    <% else %>
    <%= link_to t(:empty_cart), clear_shopcart_path, :class => "btn btn-default",  data: { confirm: t(:are_you_sure) } %>
    <% end %>
    <%= link_to t(:continue_shopping), books_path, :class => "btn btn-primary" %>
  </div>
  <div class="col-md-6 right-btns">
   
    <%= form_tag(order_steps_path, method: "get") do %>
      <% if defined?(@order) && @order.cupon.nil? %>
        <%= text_field_tag("cupon", nil, options = {class: 'cupon', placeholder: t(:cupon_code)} ) %>
      <% end %>
      <a href="<%= order_steps_path %>" id="checkout" class="btn btn-success pull-right checkout-btn"><%= t(:checkout) %></a>
      <input type="button" class="btn btn-default pull-right" value="<%= t(:update) %>" id="update" name="commit">
    <% end %>
  </div>
</div>
<% end %>
<div class="cart_empty" <%= 'hidden' unless @books.empty? %>>
  <h4><%= t(:cart_empty) %></h4>
</div>

app/views/orders/show.haml
.checkout
  .row
    .col-md-12
      %h2
        #{t(:order)} # #{@order.id}
  .row
    .col-md-3
      %h3= t(:shipping_address)
      = render partial: "orders/partials/address_data", locals: {address: @order.billing_address}
    .col-md-3
      %h3= t(:billing_address)
      = render partial: "orders/partials/address_data", locals: {address: @order.shipping_address}
    .col-md-3
      %h3= t(:shipments)
      %div
        UPS two day (#{number_to_currency(@order.delivery.to_f)})
    .col-md-3
      %h3= t(:payment_information)
      %div
        **** **** **** #{@order.credit_card.number.split("").last(4).join("")}
      %div
        = @order.credit_card.expiration_month
        \/#{@order.credit_card.expiration_year}
  - unless @order.order_items.empty?
    %h2.underlined-h2= t(@order.state.to_sym)
    .row.cart
      .col-md-12
        %table.table
          = render partial: "orders/partials/books_header"
          = render partial: "orders/partials/render_items", locals: {obj: @order, qty_change: false}
      .col-md-6
        = link_to(t(:back_to_order), orders_path, html_options = { class: "btn btn-primary lnk-to-cart"})
      .col-md-2
      = render partial: "/order_steps/partials/order_summary"
    %br/
  %br/
  %br/