config/routes.rb
Rails.application.routes.draw do

  get "/users/edit" => "users#settings"
  

  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "/:locale" do

    devise_for :users, skip: :omniauth_callbacks, :controllers => {:registrations => "users/registrations",
                                                                   :sessions      => "users/sessions" }

    resources :books
    resources :categories
    resources :orders
    resources :order_items
    resources :order_steps
    resources :addresses
    resources :users

    root 'books#home'
    get  '/settings',    to: 'users#settings'
    get  '/shop/search', to: 'books#search'
    get  '/clear_shopcart', to: 'orders#clear_cookies_shopcart'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  resources :books, only: [:index, :show], path: '/shop'
  resources :categories, only: [:show], path: '/shop/category/'
  resources :ratings, only: [:index, :create], path: '/rating'

  scope :orders do 
    put    '/update_shopcart_ajax', to: 'orders#update_shopcart_ajax'
    post    '/check_cupon_ajax', to: 'orders#check_cupon_ajax'
  end
  resources :orders

  resources :order_items

  devise_scope :user do
    get    '/settings', to: 'users#settings'
  end

  resources :order_steps
  resources :addresses, only: [:update]
  resources :users, only: [:settings, :update_data] do
    patch  '/update_data', to: 'users#update_data'
    patch  '/update_password', to: 'users#update_password'
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  validates :total_price, :state, presence: true
  before_validation :set_completed_date

  has_many :order_items, dependent: :destroy
  belongs_to :user
  belongs_to :credit_card

  has_one :billing_address, class_name: 'Address', foreign_key: 'order_billing_address_id'
  has_one :shipping_address, class_name: 'Address', foreign_key: 'order_shipping_address_id'
  has_one :cupon

  def state_enum
    %w(in_progress
       in_queue
       in_delivery
       delivered
       canceled)
  end

  aasm column: 'state', whiny_transitions: false do 
    state :in_progress, initial: true
    state :in_queue
    state :in_delivery 
    state :delivered 
    state :canceled

    event :process do
      transitions from: :in_progress, to: :in_queue
    end

    event :ship do
      transitions from: :in_queue, to: :in_delivery
    end

    event :complete do
      transitions from: [:in_queue, :in_delivery], to: :delivered
    end

    event :cancel do
      transitions from: [:in_queue, :in_delivery], to: :canceled
    end
  end

  def delivery_enum
    [['UPS Ground', '5.0'], ['UPS One Day', '10.0'], ['UPS Two Days', '20.0']]
  end

  scope :last_order_queue, -> (current_user) { 
    where(user_id: current_user.id, state: 'in_queue').last 
  }

  scope :in_queue, -> (current_user) { 
    where(user_id: current_user.id, state: 'in_queue').all 
  }

  scope :in_delivery, -> (current_user) {
    where(user_id: current_user.id, state: 'in_delivery').all
  }

  scope :delivered, -> (current_user) {
    where(user_id: current_user.id, state: 'delivered').all
  }

  def self.create_order(cookies, total_price, user_id)
    book_count = cookies.nil? ? 0 : cookies['book_count']
    order = Order.create(user_id: user_id,
                          total_price: total_price,
                          order_total: total_price + 5.0,
                          book_count: book_count.to_i)
    order.id
  end

  private
  
  def set_completed_date
    self.completed_date = 3.days.from_now
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :load_in_progress_order, only: [:show]
  load_and_authorize_resource except: [:update_shopcart_ajax, 
    :clear_cookies_shopcart,
     :check_cupon_ajax]

  def new
    get_books
  end

  def update_shopcart_ajax
    set_session(ShopcartUpdateService.new(@order, params).call)
    render nothing: true
  end

  def clear_cookies_shopcart
    cookies_delete
    redirect_to books_path
  end

  def check_cupon_ajax
    checking = Cupon.cheking(params[:value])
    msg = checking.empty? ? 'This code is not found' : checking_message(checking.first)
    render text: msg
  end

  def show
  end

  def index
    get_books
    [:in_queue, :in_delivery, :delivered].each do |item|
      instance_variable_set("@#{item}".to_sym,
        Order.public_send(item).last_by_current_user(current_user))
    end
  end

  def destroy
    clear_order
    cookies_delete
    set_session(0)
    redirect_to books_path
  end

  private

  def checking_message(first)
    str = 'Your discount is $' << first.discount.to_s << '. Continue?'
    first.use ? 'This code has been used' : str
  end

  def clear_order
    @order.order_items.destroy_all
    @order.update(total_price: 0.0, book_count: 0, order_total: 0.0)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/partials/_address_data.haml
%div= address.firstname
%div= address.address
%div= address.city
%div= User.country_name(address.country)
%div= address.phone

app/views/orders/partials/_books_header.haml
%thead
  %tr
    %td= t(:book)
    %td= t(:price)
    %td= t(:qty)
    %td= t(:total)

app/views/orders/partials/_render_books.haml
%tbody
  - books.try(:each) do |book|
    %tr.tr
      %td
        = link_to "#{image_tag book.image_url :resize_to_cart} #{book.title}".html_safe, book
      %td.book_price= number_to_currency(book.price)
      %td.count
        - if qty_change
          %input.quantity-input{:id => "quantity_#{book.id}", :max => "100", :min => "1", :name => "quantity-input", :type => "number", :value => "#{items_calc(book, true)}"}/
        - else
          = items_calc(book, true)
      %td.total= items_calc(book)
      - if remove_link
        %td.remove_link
          = link_to "<span aria-hidden='true'>&times;</span>".html_safe , 'javascript:void(0)', id: "id_" << book.id.to_s

app/views/orders/partials/_render_items.haml
%tbody
  - obj.order_items.try(:each) do |item|
    %tr.tr
      %td
        = link_to "#{image_tag item.book.image_url :resize_to_cart} #{item.book.title}".html_safe, item.book
      %td.book_price= number_to_currency(item.book.price)
      %td.count
        - if qty_change
          %input.quantity-input{:id => "quantity_#{book.id}", :max => "100", :min => "1", :name => "quantity-input", :type => "number", :value => "#{item.quantity}"}/
        - else
          = item.quantity
      %td.total= number_to_currency(item.book.price * item.quantity.to_i)

app/views/orders/partials/_status.haml
- unless status.empty?
  %h2.underlined-h2= title
  %table.table
    %thead
      %tr
        %td= t(:number)
        %td= t(:completed_at)
        %td= t(:total)
        %td= t(:details)
    %tbody
      - status.try(:each) do |order|
        %tr
          %td= order.id
          %td= order.completed_date
          %td= number_to_currency(order.order_total)
          %td= link_to t(:view), order_path(order)