config/routes.rb
Rails.application.routes.draw do

  get "/users/edit" => "users#settings"
  

  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "/:locale" do

    devise_for :users, skip: :omniauth_callbacks, :controllers => {:registrations => "users/registrations",
                                                                   :sessions      => "users/sessions" }

    resources :books
    resources :categories
    resources :orders
    resources :order_items
    resources :order_steps
    resources :addresses
    resources :users

    root 'books#home'
    get  '/settings',    to: 'users#settings'
    get  '/shop/search', to: 'books#search'
    get  '/clear_shopcart', to: 'orders#clear_cookies_shopcart'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  resources :books, only: [:index, :show], path: '/shop'
  resources :categories, only: [:show], path: '/shop/category/'
  resources :ratings, only: [:index, :create], path: '/rating'

  scope :orders do 
    put    '/update_shopcart_ajax', to: 'orders#update_shopcart_ajax'
    post    '/check_cupon_ajax', to: 'orders#check_cupon_ajax'
  end
  resources :orders

  resources :order_items

  devise_scope :user do
    get    '/settings', to: 'users#settings'
  end

  resources :order_steps
  resources :addresses, only: [:update]
  resources :users, only: [:settings, :update_data] do
    patch  '/update_data', to: 'users#update_data'
    patch  '/update_password', to: 'users#update_password'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many   :ratings
  has_many   :books, through: :ratings
  has_many   :orders, dependent: :destroy

  has_one :billing_address, class_name: 'Address', foreign_key: 'user_billing_address_id'
  has_one :shipping_address, class_name: 'Address', foreign_key: 'user_shipping_address_id'

  validates :firstname, :lastname, presence: true

  mount_uploader :image, FacebookAvatarUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.firstname = auth.info.first_name
      user.lastname = auth.info.last_name
      user.facebook_image = auth.info.image
    end
  end

  def custom_label_method
    self.firstname + self.lastname
  end

  def self.country_name(country_code)
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      I18n.locale = session[:omniauth_login_locale] || I18n.default_locale
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  # DELETE /resource
  def destroy
    cookies_delete
    super
  end

  protected

  def after_sign_up_path_for(_resource)
    after_sign_up # unless  request.env['omniauth.origin']
    root_path
  end

  # before_filter :configure_sign_up_params, only: [:create]
  # before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  #def destroy
  #  cookies_delete
  #  super
  #end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_filter :configure_sign_in_params, only: [:create]

  def destroy
    cookies.delete :user_products_count
    session[:user_products_count] = ''
    super
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :create_addresses_obj
  before_action :authenticate_user!
  before_action :authorize_current_user

  def update_password
    bool = current_user.valid_password?(params[:user][:old_password])
    bool ? updates : flash.now[:alert] = 'Incorrect password'
    current_user.errors.messages[:password_form] = true
    render "users/settings"
  end

  def update_data
    updates
    current_user.errors.messages[:data_form] = true
    render "users/settings"
  end

  private

  def authorize_current_user
    authorize! :update, current_user
  end

  def updates
    #@user = User.find(current_user.id)
    if current_user.update(user_params)
      sign_in current_user, :bypass => true
      flash.now[:notice] = 'Your data have been changes'
    else
      flash.now[:alert] = 'Something went wrong'
    end
  end

  def user_params
    params.require(:user).permit(:firstname, 
                                 :lastname, 
                                 :email, 
                                 :password, 
                                 :user_id, 
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def validate_class(form_type, field)
    text = 'form-control'
    if @resource
      error_massages = @resource.errors.messages 
      if error_massages[form_type] && !error_massages[field].empty?
        text << ' error'
      end
    end
    text
  end

  def show_errors(obj, form_type)
    string = '' 
    error_massages = obj ? obj.errors.messages : nil
    if error_massages && error_massages[form_type] == true
      error_massages.keys.each do |key, _value|
        string << '<span class="error_message">'
        string << "#{key} - " << error_massages[key][0] if key != form_type
        string << '</span><br>'
      end
      string << "<div id='shipping_error' class='has_errors'></div>" if error_massages[:shipping_form] == true
    end
    string.html_safe
  end

  def clear_obj
    current_user.errors.messages.except!(:name_email_firstname, :email, :lastname, :firstname)
  end
end

app/views/users/partials/_billing_address.haml
.col-md-6
  %h2.underlined-h2.add-margin-bot= t(:billing_address)
  .row
    .col-md-8
      = show_errors(@billing_address, :billing_form)
      = form_for @billing_address, url: address_path(current_user),  html: {class: "nifty_form", method: "patch"} do |f|
        = render partial: "users/partials/billing_shipping", locals: {address: @billing_address, form: 'billing_form'.to_sym, type: 'billing', resource: @resource, user: current_user, shipping: false, f: f}

app/views/users/partials/_billing_shipping.haml
- @resource = resource
.form-group
  = f.label :firstname, t(:first_name), class: "control-label"
  = f.text_field :firstname, {class: validate_class(form, :firstname), placeholder: t(:first_name)}
.form-group
  = f.label :lastname, t(:last_name), class: "control-label"
  = f.text_field :lastname, {class: validate_class(form, :lastname), placeholder: t(:last_name)}
.form-group
  = f.label :address, t(:street_address), class: "control-label"
  = f.text_field :address, {class: validate_class(form, :address), placeholder: t(:street_address)}
.form-group
  = f.label :city, t(:city), class: "control-label"
  = f.text_field :city, {class: validate_class(form, :city), placeholder: t(:city)}
.form-group
  = f.label :country, "Country", class: "control-label"
  - if address.country && !address.country.empty?
    = country_select("address", "country", { selected: address.country }, { class: 'form-control', name: 'address[country]' })
  - else
    = country_select("address", "country", { include_blank: t(:select_a_country)}, { class: validate_class(form, :country), name: 'address[country]' })
.form-group
  = f.label :zipcode, t(:zip), class: "control-label"
  = f.text_field :zipcode, {class: validate_class(form, :zipcode), placeholder: t(:zip) }
.form-group
  = f.label :phone, t(:phone), class: "control-label"
  = f.text_field :phone, {class: validate_class(form, :phone), placeholder: t(:phone)}
  = hidden_field(:address, :type, value: type )
  -unless shipping
    = hidden_field(:address, :and_shipping, value: 'true' )
.form-group
  = f.submit t(:save), class: "btn btn-primary"

app/views/users/partials/_name_and_email.haml
.col-md-6
  %h2.underlined-h2.add-margin-bot{:style => "margin-bottom: 12px;"}=t(:name_and_email)
  .row
    .col-md-8
      = show_errors(current_user, :data_form)
      = form_for current_user, url: user_update_data_path(current_user),  html: {class: "nifty_form"} do |f|
        .form-group
          = f.label :name_email_firstname, t(:first_name), class: "control-label"
          = f.text_field :firstname, {class: validate_class('data_form', 'firstname') , placeholder: t(:first_name) }
        .form-group
          = f.label :lastname, t(:last_name), class: "control-label"
          = f.text_field :lastname, {class: validate_class('data_from', 'lastname'), placeholder: t(:last_name) }
        .form-group
          = f.label :email, t(:email), class: "control-label"
          = f.text_field :email, {class: validate_class('data_form', 'email'), placeholder: t(:email) }
        .form-group
          %input.btn.btn-primary{:name => "commit", :type => "submit", :value => t(:save)}

app/views/users/partials/_password.haml
.col-md-6
  %h2.underlined-h2.add-margin-bot.mb12=t(:password)
  .row
    .col-md-8
      - clear_obj
      = show_errors(current_user, :password_form)
      - if current_user.provider == nil
        = form_for current_user, url: user_update_password_path(current_user),  html: {class: "nifty_form"} do |f|
          .form-group
            = f.label :old_password, t(:old_password), class: "control-label"
            = f.password_field :old_password, {class: validate_class('password_form', 'old_password') }
          .form-group
            = f.label :new_password, t(:new_password), class: "control-label"
            = f.password_field :password, {class: validate_class('password_form', 'password') }
            %em= t(:eight_characters)
          .form-group
            %input.btn.btn-primary{:name => "commit", :type => "submit", :value => t(:change_password)}/
      - else
        %p= t(:not_change_password)

app/views/users/partials/_remove_account.haml
%h2.underlined-h2= t(:remove_account)
= button_to t(:remove_account), registration_path('user'), data: { confirm: t(:are_you_sure) }, method: :delete, class: 'btn btn-primary disabled', id: 'remove_button', name: 'remove_accaunt_checkbox'
= check_box_tag 'remove_accaunt_checkbox', 'false'
%em#em_delete= t(:data_lost)

app/views/users/partials/_shipping_address.haml
.col-md-6
  %h2.underlined-h2.add-margin-bot.mb12= t(:shipping_address)
  .row
    .col-md-8
      = show_errors(@shipping_address, :shipping_form)
      = form_for @shipping_address, url: address_path(current_user),  html: {class: "nifty_form", method: "patch"} do |f|
        .form-group.checkit
          = f.label :label, t(:use_billing_address)
          = f.check_box :checkbox, {:checked=>true}
          
        #shipping_address
          = render partial: "users/partials/billing_shipping", locals: {address: @shipping_address, form: 'shipping_form'.to_sym, type: 'shipping', resource: @resource, user: current_user, shipping: true, f: f}