config/routes.rb
Rails.application.routes.draw do

  get "/users/edit" => "users#settings"
  

  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "/:locale" do

    devise_for :users, skip: :omniauth_callbacks, :controllers => {:registrations => "users/registrations",
                                                                   :sessions      => "users/sessions" }

    resources :books
    resources :categories
    resources :orders
    resources :order_items
    resources :order_steps
    resources :addresses
    resources :users

    root 'books#home'
    get  '/settings',    to: 'users#settings'
    get  '/shop/search', to: 'books#search'
    get  '/clear_shopcart', to: 'orders#clear_cookies_shopcart'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  resources :books, only: [:index, :show], path: '/shop'
  resources :categories, only: [:show], path: '/shop/category/'
  resources :ratings, only: [:index, :create], path: '/rating'

  scope :orders do 
    put    '/update_shopcart_ajax', to: 'orders#update_shopcart_ajax'
    post    '/check_cupon_ajax', to: 'orders#check_cupon_ajax'
  end
  resources :orders

  resources :order_items

  devise_scope :user do
    get    '/settings', to: 'users#settings'
  end

  resources :order_steps
  resources :addresses, only: [:update]
  resources :users, only: [:settings, :update_data] do
    patch  '/update_data', to: 'users#update_data'
    patch  '/update_password', to: 'users#update_password'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body style="position: relative;">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <span class="navbar-brand" href="<%= root_path %>">The Bookstore</span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%= cp(root_path) %>><%= link_to t(:home), root_path %></li>
        <li <%= cp(books_path) %>><%= link_to t(:shop), books_path %></li>
        <form id="search" class="navbar-form navbar-left" action="<%= shop_search_path %>" role="search" method="get">
          <div class="form-group">
            <input type="text" name="value" id="field_search" value="<%= params[:value] if params[:action] == "search" %>" class="form-control" placeholder="<%= t(:search) %>">
          </div>
          <button type="submit" class="btn btn-default"><%= t(:search) %></button>
        </form>
        <li class="cart-lnk  <%= cp(new_order_path, true) %>">
            <a href="<%= new_order_path %>"><span class="glyphicon glyphicon-shopping-cart"></span><%= t(:cart) %>:<em>(<%= count_products %>)</em>
        </a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <span style="padding-top: 14px; margin-right: 10px; color: green; font-weight: bold; float: left;"><%= current_user.firstname %></span>
          <% if current_user.admin? %>
            <li><%= link_to t(:admin_panel), rails_admin.dashboard_path %></li>
          <% end %> 
          <li <%= cp(settings_path) %> ><%= link_to t(:settings), settings_path %></li>
          <li <%= cp(orders_path) %> ><%= link_to t(:orders), orders_path %></li>

          <li <%= cp(destroy_user_session_path) %> >
           <%= link_to(t(:sign_out), destroy_user_session_path, :method => :delete) %>   
          </li>
          <li class="multi-languages">
            <%= link_to 'en', url_for( :locale => 'en' ) %>
            <%= link_to 'ru', url_for( :locale => 'ru' ) %>
          </li>
        <% else %>
          <li <%= cp(new_user_session_path) %> >
            <%= link_to t(:log_in), new_user_session_path %>
          </li>

          <li <%= cp(new_user_registration_path) %> >
            <%= link_to t(:sign_up), new_user_registration_path %>
          </li>

           <li class="multi-languages">
            <%= link_to 'en', url_for( :locale => 'en' ) %>
            <%= link_to 'ru', url_for( :locale => 'ru' ) %>
          </li>

        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">

 <% if notice.class === "String" %>
  <div class="alert alert-success fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
 <% end %>

  <% if alert.class === "String" %>
  <div class="alert alert-danger fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
 <% end %>
  
</div>

<div class="container">
<% unless render_breadcrumbs == "" %>
<ol class="breadcrumb">
   <%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>
<% end %>

  <%= yield %>

</div>

<div style="display:none" id="current_user"><%= current_user.id if current_user %></div>

</body>
</html>